########################################################################
#
# title:       Docker Compose YAML file for DEV-PAAS
# author:      Marco Maccio (http://marmac.name)
# url:         https://github.com/marcomaccio/devpaas-docker
# description: Builds (4) images, pulls (2) images, and builds (9) containers,
#              for the Development PAAS example REST API
# to run:      docker-compose -p <solutionName> up -d
#
########################################################################

cis-dv:
  image: jenkins
  volumes:
   - /var/jenkins_home

cis:
  build: jenkins/
  ports:
   - "8080:8080"
   - "50000:50000"
  #expose:
  #  - "8080"
  volumes_from:
   - cis-dv
  links:
   - cis-dv
  extra_hosts:
    - "devpaas.marmac:192.168.99.100"

graphite:
  image: hopsoft/graphite-statsd:latest
  ports:
   - "8500:80"

elk:
  build: elk/
  ports:
    - "8200:80"       # kibana
    - "5000:5000/udp" # logspout
    - "5001:5001/udp" # log4j2 socket appender
    - "9200:9200"     # elasticsearch

logspout:
  build: logspout/
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"
  links:
    - elk
  ports:
   - "8000:80"        # html message debugging
  environment:
    - ROUTE_URIS=logstash://elk:5000

nginx:
  build: nginx/
  ports:
   - "80:80"
  links:
   - cis
