# ELK stack for Virtual-Vehicles Dockerfile

FROM willdurand/elk

MAINTAINER Marco Maccio <marco.maccio@marmac.name>

ENV REFRESHED_AT 2016-02-23

COPY logstash-logspout.conf /etc/logstash/logstash-logspout.conf
