# Logspout with Logstash

# https://github.com/looplab/logspout-logstash
# https://github.com/gliderlabs/logspout/tree/master/custom
# builds with modules.go in project root (not here)
# test: nc elk 5000 < /dev/null; echo $? # return 0 if working

FROM gliderlabs/logspout:master

MAINTAINER Marco Maccio <marco.maccio@marmac.name>

ENV REFRESHED_AT 2016-02-23
